// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xppxwplwejbiewhzqimy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcHh3cGx3ZWpiaWV3aHpxaW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODMzODMsImV4cCI6MjA2ODI1OTM4M30.GbK8jnkj65CgKpgQmeoN9MjkOZBPj4SeXME-_IM1de0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});