// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swvmdgupswnhrcoucjml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dm1kZ3Vwc3duaHJjb3Vjam1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzMzMTcsImV4cCI6MjA2ODM0OTMxN30.7a8c7VumPs-4qKTrWX6psRkM7JpSh12chXA8Y523Nbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});